In [1]:
import numpy as np
from tqdm import tqdm
from sklearn.neighbors import NearestNeighbors
from utils import read_canonical_model, load_pc, visualize_icp_result, multi_icp, o3d_icp
source_pc = read_canonical_model("liq_container")
target_pc = load_pc("liq_container", 1)
pose = np.eye(4)

Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.


In [23]:
T = multi_icp(source_pc, target_pc)
visualize_icp_result(source_pc, target_pc, T)

RegistrationResult with fitness=1.000000e+00, inlier_rmse=3.057865e-02, and correspondence_set size of 46563
Access transformation to get result.
Transformation is:
[[ 0.43298923  0.78777549 -0.43809827  0.69257193]
 [-0.87713564  0.4802309  -0.00336945 -0.0487757 ]
 [ 0.20773396  0.38573054  0.89892077 -0.00484611]
 [ 0.          0.          0.          1.        ]]
[[ 0.43298923  0.78777549 -0.43809827  0.69257193]
 [-0.87713564  0.4802309  -0.00336945 -0.0487757 ]
 [ 0.20773396  0.38573054  0.89892077 -0.00484611]
 [ 0.          0.          0.          1.        ]]


In [2]:
# Run ICP
R, t, error = multi_icp(source_pc, target_pc, trial=2)
pose[:3, :3] = R
pose[:3, 3] = t
print(pose)
visualize_icp_result(source_pc, target_pc, pose)

[[ 0.42346914  0.79299783 -0.43798211  0.69317185]
 [-0.88394467  0.46752003 -0.00817596 -0.04866781]
 [ 0.19828189  0.39061422  0.89894651 -0.00596629]
 [ 0.          0.          0.          1.        ]]


In [ ]:
# visualize the estimated result
